### import modules

In [17]:
import pandas as pd
import numpy as np

### Create dataframe

In [18]:
raw_data = {'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'last_name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze'], 
        'age': [42, 52, 36, 24, 73], 
        'preTestScore': [4, 24, 31, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70]}
df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'preTestScore', 'postTestScore'])
df

first_name last_name  age  preTestScore  postTestScore
0      Jason    Miller   42             4             25
1      Molly  Jacobson   52            24             94
2       Tina       Ali   36            31             57
3       Jake    Milner   24             2             62
4        Amy     Cooze   73             3             70

### Select a random subset of 2 without replacement

In [19]:
df.take(np.random.permutation(len(df))[:2])

first_name last_name  age  preTestScore  postTestScore
3       Jake    Milner   24             2             62
0      Jason    Miller   42             4             25

In [27]:
np.random.permutation(len(df))

array([1, 0, 2, 3, 4])

In [26]:
np.random.permutation(df.shape[0])

array([2, 3, 4, 1, 0])

In [21]:
np.random.permutation(df)

array([['Molly', 'Jacobson', 52, 24, 94],
       ['Amy', 'Cooze', 73, 3, 70],
       ['Tina', 'Ali', 36, 31, 57],
       ['Jason', 'Miller', 42, 4, 25],
       ['Jake', 'Milner', 24, 2, 62]], dtype=object)

In [28]:
np.random.permutation(df.index)

array([2, 1, 0, 3, 4], dtype=int64)